name: Absensi Otomatis

on:
  schedule:
    # Selasa
    - cron: '50 3 * * 2'  # 10:50 WIB
    - cron: '35 9 * * *'  # 16.35 WIB
    
    # Rabu
    - cron: '5 1 * * 3'   # 08:05 WIB
    - cron: '50 3 * * 3'  # 10:50 WIB
    - cron: '5 7 * * 3'   # 14:05 WIB

    # Kamis
    - cron: '5 1 * * 3'   # 08:05 WIB
    - cron: '5 7 * * 4'   # 14:05 WIB
    - cron: '50 3 * * 3'  # 10:50 WIB

    # Jumat
    - cron: '5 1 * * 3'   # 08:05 WIB

  workflow_dispatch:
jobs:
  run-absen:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil kode dari repository
        uses: actions/checkout@v4

      - name: 2. Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: 3. Siapkan lingkungan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: 4. Install library dari requirement.txt
        run: pip install -r requirement.txt

      - name: 5. Jalankan skrip absen
        env:
          NPM: ${{ secrets.NPM }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python -u absen.py
